### ISSUE TITLE
可以把打包环境发我一份吗，或者教我安装打包环境的。3452003860@qq.com

### ISSUE THREAD

**Issue by chenzhenpin** [xiaoyaoking/kivy-android-webview#1]

**Comment by xiaoyaoking** [comment]
kivy中文文档
https://github.com/nkiiiiid/Kivy-CN
kivy打包环境虚拟机，kivy调试
https://github.com/nkiiiiid/kivy-apk
打包虚拟机微云镜像
https://share.weiyun.com/39ef0b9ac51228238569d433dbb94e7c
kivy打包环境搭建指南
https://github.com/nkiiiiid/kivydev-note

**Comment by chenzhenpin** [comment]
还没有用，不过先谢谢的。
